# Generated by Django 4.0.6 on 2022-08-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='8kx7ptSv', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='circuit_id',
            field=models.CharField(default='VvGZjiQt', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_id',
            field=models.CharField(default='BWesVhyc', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='building',
            table='building_data',
        ),
    ]
