# Generated by Django 4.0.6 on 2022-08-01 01:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sustainergy_dashboard', '0002_alter_building_building_id_alter_circuit_circuit_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='building',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='circuit',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='panel',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='panel',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_id',
            field=models.CharField(default='cYqvycff', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='circuit',
            name='circuit_id',
            field=models.CharField(default='6MKgBCEz', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='panel',
            name='panel_id',
            field=models.CharField(default='KpvxPas8', max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('client_id', models.CharField(default='98RdFEiW', max_length=30, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('province', models.CharField(max_length=30)),
                ('postal_code', models.CharField(max_length=30)),
                ('photo_id', models.CharField(max_length=30)),
                ('buildings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sustainergy_dashboard.building')),
            ],
            options={
                'db_table': 'client_data',
            },
        ),
    ]
